"""create goshuin tables

Revision ID: 0f42a934865d
Revises: b389592974f8
Create Date: 2025-02-14 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as pg


# revision identifiers, used by Alembic.
revision: str = "0f42a934865d"
down_revision: Union[str, None] = "b389592974f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


spot_type_enum = sa.Enum(
    "shrine", "temple", "museum", "other", name="spot_type"
)
goshuin_status_enum = sa.Enum(
    "planned", "collected", "missed", name="goshuin_status"
)
goshuin_acquisition_method_enum = sa.Enum(
    "in_person", "by_mail", "event", "online", name="goshuin_acquisition_method"
)
spot_image_type_enum = sa.Enum(
    "exterior", "interior", "map", "other", name="spot_image_type"
)
goshuin_image_type_enum = sa.Enum(
    "stamp_front", "stamp_back", "cover", "other", name="goshuin_image_type"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spots",
        sa.Column("id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("spot_type", spot_type_enum, nullable=False),
        sa.Column("prefecture", sa.String(length=100), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("website_url", sa.String(length=255), nullable=True),
        sa.Column("phone_number", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            server_onupdate=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="uq_spots_slug"),
        sa.CheckConstraint(
            "latitude >= -90 AND latitude <= 90", name="ck_spots_latitude_range"
        ),
        sa.CheckConstraint(
            "longitude >= -180 AND longitude <= 180", name="ck_spots_longitude_range"
        ),
    )
    op.create_index("ix_spots_prefecture", "spots", ["prefecture"], unique=False)
    op.create_index("ix_spots_spot_type", "spots", ["spot_type"], unique=False)

    op.create_table(
        "goshuin_records",
        sa.Column("id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("spot_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("visit_date", sa.Date(), nullable=False),
        sa.Column("acquisition_method", goshuin_acquisition_method_enum, nullable=False),
        sa.Column("status", goshuin_status_enum, nullable=False),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            server_onupdate=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["spot_id"], ["spots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "spot_id", "visit_date", name="uq_goshuin_records_unique_visit"
        ),
        sa.CheckConstraint(
            "rating IS NULL OR (rating >= 1 AND rating <= 5)",
            name="ck_goshuin_records_rating_range",
        ),
    )
    op.create_index(
        "ix_goshuin_records_user_id", "goshuin_records", ["user_id"], unique=False
    )
    op.create_index(
        "ix_goshuin_records_spot_id", "goshuin_records", ["spot_id"], unique=False
    )

    op.create_table(
        "spot_images",
        sa.Column("id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("spot_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=False),
        sa.Column("image_type", spot_image_type_enum, nullable=False),
        sa.Column(
            "is_primary",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "display_order",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["spot_id"], ["spots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "spot_id", "display_order", name="uq_spot_images_spot_id_display_order"
        ),
    )
    op.create_index("ix_spot_images_spot_id", "spot_images", ["spot_id"], unique=False)

    op.create_table(
        "goshuin_images",
        sa.Column("id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("goshuin_record_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=False),
        sa.Column("image_type", goshuin_image_type_enum, nullable=False),
        sa.Column(
            "display_order",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["goshuin_record_id"], ["goshuin_records.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "goshuin_record_id", "display_order", name="uq_goshuin_images_display_order"
        ),
    )
    op.create_index(
        "ix_goshuin_images_record_id",
        "goshuin_images",
        ["goshuin_record_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_goshuin_images_record_id", table_name="goshuin_images")
    op.drop_table("goshuin_images")
    op.drop_index("ix_spot_images_spot_id", table_name="spot_images")
    op.drop_table("spot_images")
    op.drop_index(
        "ix_goshuin_records_spot_id", table_name="goshuin_records"
    )
    op.drop_index(
        "ix_goshuin_records_user_id", table_name="goshuin_records"
    )
    op.drop_table("goshuin_records")
    op.drop_index("ix_spots_spot_type", table_name="spots")
    op.drop_index("ix_spots_prefecture", table_name="spots")
    op.drop_table("spots")

    goshuin_image_type_enum.drop(op.get_bind(), checkfirst=True)
    spot_image_type_enum.drop(op.get_bind(), checkfirst=True)
    goshuin_acquisition_method_enum.drop(op.get_bind(), checkfirst=True)
    goshuin_status_enum.drop(op.get_bind(), checkfirst=True)
    spot_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
